//------------------------------------------------------------------------------
// <auto-generated>
//     This code was generated from a template.
//
//     Manual changes to this file may cause unexpected behavior in your application.
//     Manual changes to this file will be overwritten if the code is regenerated.
// </auto-generated>
//------------------------------------------------------------------------------

namespace Capa_AccesoDatos.Model
{
    using System;
    using System.Collections.Generic;

    public partial class Bandas
    {
        [System.Diagnostics.CodeAnalysis.SuppressMessage("Microsoft.Usage", "CA2214:DoNotCallOverridableMethodsInConstructors")]
        public Bandas()
        {
            this.Conciertos = new HashSet<Conciertos>();
        }
    
        public int IdBanda { get; set; }
        public string Nombre { get; set; }
        public string AnoFundacion { get; set; }
        public string Genero { get; set; }

        [System.Diagnostics.CodeAnalysis.SuppressMessage("Microsoft.Usage", "CA2227:CollectionPropertiesShouldBeReadOnly")]
        public virtual ICollection<Conciertos> Conciertos { get; set; }
    }
}
