//------------------------------------------------------------------------------
// <auto-generated>
//     This code was generated from a template.
//
//     Manual changes to this file may cause unexpected behavior in your application.
//     Manual changes to this file will be overwritten if the code is regenerated.
// </auto-generated>
//------------------------------------------------------------------------------

namespace Capa_AccesoDatos.Model
{
    using System;
    using System.Collections.Generic;
    
    public partial class Conciertos
    {
        public int IdConcierto { get; set; }
        public string Pais { get; set; }
        public System.DateTime FechaPresentacion { get; set; }
        public string Lugar { get; set; }
        public int IdBanda { get; set; }
    
        public virtual Bandas Bandas { get; set; }
    }
}
